/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface GovernedFinalizableInterface extends utils.Interface {
  functions: {
    "finalize()": FunctionFragment;
    "isFinalized()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "finalize" | "isFinalized"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "finalize", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isFinalized",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "finalize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isFinalized",
    data: BytesLike
  ): Result;

  events: {
    "Finalized()": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Finalized"): EventFragment;
}

export interface FinalizedEventObject {}
export type FinalizedEvent = TypedEvent<[], FinalizedEventObject>;

export type FinalizedEventFilter = TypedEventFilter<FinalizedEvent>;

export interface GovernedFinalizable extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: GovernedFinalizableInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    finalize(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    isFinalized(overrides?: CallOverrides): Promise<[boolean]>;
  };

  finalize(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  isFinalized(overrides?: CallOverrides): Promise<boolean>;

  callStatic: {
    finalize(overrides?: CallOverrides): Promise<void>;

    isFinalized(overrides?: CallOverrides): Promise<boolean>;
  };

  filters: {
    "Finalized()"(): FinalizedEventFilter;
    Finalized(): FinalizedEventFilter;
  };

  estimateGas: {
    finalize(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    isFinalized(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    finalize(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    isFinalized(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
