/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  Signer,
  utils,
} from "ethers";
import type { EventFragment } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface IStarknetMessagingEventsInterface extends utils.Interface {
  functions: {};

  events: {
    "ConsumedMessageToL1(uint256,address,uint256[])": EventFragment;
    "ConsumedMessageToL2(address,uint256,uint256,uint256[],uint256)": EventFragment;
    "LogMessageToL1(uint256,address,uint256[])": EventFragment;
    "LogMessageToL2(address,uint256,uint256,uint256[],uint256,uint256)": EventFragment;
    "MessageToL2Canceled(address,uint256,uint256,uint256[],uint256)": EventFragment;
    "MessageToL2CancellationStarted(address,uint256,uint256,uint256[],uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ConsumedMessageToL1"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ConsumedMessageToL2"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogMessageToL1"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogMessageToL2"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MessageToL2Canceled"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "MessageToL2CancellationStarted"
  ): EventFragment;
}

export interface ConsumedMessageToL1EventObject {
  fromAddress: BigNumber;
  toAddress: string;
  payload: BigNumber[];
}
export type ConsumedMessageToL1Event = TypedEvent<
  [BigNumber, string, BigNumber[]],
  ConsumedMessageToL1EventObject
>;

export type ConsumedMessageToL1EventFilter =
  TypedEventFilter<ConsumedMessageToL1Event>;

export interface ConsumedMessageToL2EventObject {
  fromAddress: string;
  toAddress: BigNumber;
  selector: BigNumber;
  payload: BigNumber[];
  nonce: BigNumber;
}
export type ConsumedMessageToL2Event = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber[], BigNumber],
  ConsumedMessageToL2EventObject
>;

export type ConsumedMessageToL2EventFilter =
  TypedEventFilter<ConsumedMessageToL2Event>;

export interface LogMessageToL1EventObject {
  fromAddress: BigNumber;
  toAddress: string;
  payload: BigNumber[];
}
export type LogMessageToL1Event = TypedEvent<
  [BigNumber, string, BigNumber[]],
  LogMessageToL1EventObject
>;

export type LogMessageToL1EventFilter = TypedEventFilter<LogMessageToL1Event>;

export interface LogMessageToL2EventObject {
  fromAddress: string;
  toAddress: BigNumber;
  selector: BigNumber;
  payload: BigNumber[];
  nonce: BigNumber;
  fee: BigNumber;
}
export type LogMessageToL2Event = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber[], BigNumber, BigNumber],
  LogMessageToL2EventObject
>;

export type LogMessageToL2EventFilter = TypedEventFilter<LogMessageToL2Event>;

export interface MessageToL2CanceledEventObject {
  fromAddress: string;
  toAddress: BigNumber;
  selector: BigNumber;
  payload: BigNumber[];
  nonce: BigNumber;
}
export type MessageToL2CanceledEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber[], BigNumber],
  MessageToL2CanceledEventObject
>;

export type MessageToL2CanceledEventFilter =
  TypedEventFilter<MessageToL2CanceledEvent>;

export interface MessageToL2CancellationStartedEventObject {
  fromAddress: string;
  toAddress: BigNumber;
  selector: BigNumber;
  payload: BigNumber[];
  nonce: BigNumber;
}
export type MessageToL2CancellationStartedEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber[], BigNumber],
  MessageToL2CancellationStartedEventObject
>;

export type MessageToL2CancellationStartedEventFilter =
  TypedEventFilter<MessageToL2CancellationStartedEvent>;

export interface IStarknetMessagingEvents extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IStarknetMessagingEventsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {};

  callStatic: {};

  filters: {
    "ConsumedMessageToL1(uint256,address,uint256[])"(
      fromAddress?: PromiseOrValue<BigNumberish> | null,
      toAddress?: PromiseOrValue<string> | null,
      payload?: null
    ): ConsumedMessageToL1EventFilter;
    ConsumedMessageToL1(
      fromAddress?: PromiseOrValue<BigNumberish> | null,
      toAddress?: PromiseOrValue<string> | null,
      payload?: null
    ): ConsumedMessageToL1EventFilter;

    "ConsumedMessageToL2(address,uint256,uint256,uint256[],uint256)"(
      fromAddress?: PromiseOrValue<string> | null,
      toAddress?: PromiseOrValue<BigNumberish> | null,
      selector?: PromiseOrValue<BigNumberish> | null,
      payload?: null,
      nonce?: null
    ): ConsumedMessageToL2EventFilter;
    ConsumedMessageToL2(
      fromAddress?: PromiseOrValue<string> | null,
      toAddress?: PromiseOrValue<BigNumberish> | null,
      selector?: PromiseOrValue<BigNumberish> | null,
      payload?: null,
      nonce?: null
    ): ConsumedMessageToL2EventFilter;

    "LogMessageToL1(uint256,address,uint256[])"(
      fromAddress?: PromiseOrValue<BigNumberish> | null,
      toAddress?: PromiseOrValue<string> | null,
      payload?: null
    ): LogMessageToL1EventFilter;
    LogMessageToL1(
      fromAddress?: PromiseOrValue<BigNumberish> | null,
      toAddress?: PromiseOrValue<string> | null,
      payload?: null
    ): LogMessageToL1EventFilter;

    "LogMessageToL2(address,uint256,uint256,uint256[],uint256,uint256)"(
      fromAddress?: PromiseOrValue<string> | null,
      toAddress?: PromiseOrValue<BigNumberish> | null,
      selector?: PromiseOrValue<BigNumberish> | null,
      payload?: null,
      nonce?: null,
      fee?: null
    ): LogMessageToL2EventFilter;
    LogMessageToL2(
      fromAddress?: PromiseOrValue<string> | null,
      toAddress?: PromiseOrValue<BigNumberish> | null,
      selector?: PromiseOrValue<BigNumberish> | null,
      payload?: null,
      nonce?: null,
      fee?: null
    ): LogMessageToL2EventFilter;

    "MessageToL2Canceled(address,uint256,uint256,uint256[],uint256)"(
      fromAddress?: PromiseOrValue<string> | null,
      toAddress?: PromiseOrValue<BigNumberish> | null,
      selector?: PromiseOrValue<BigNumberish> | null,
      payload?: null,
      nonce?: null
    ): MessageToL2CanceledEventFilter;
    MessageToL2Canceled(
      fromAddress?: PromiseOrValue<string> | null,
      toAddress?: PromiseOrValue<BigNumberish> | null,
      selector?: PromiseOrValue<BigNumberish> | null,
      payload?: null,
      nonce?: null
    ): MessageToL2CanceledEventFilter;

    "MessageToL2CancellationStarted(address,uint256,uint256,uint256[],uint256)"(
      fromAddress?: PromiseOrValue<string> | null,
      toAddress?: PromiseOrValue<BigNumberish> | null,
      selector?: PromiseOrValue<BigNumberish> | null,
      payload?: null,
      nonce?: null
    ): MessageToL2CancellationStartedEventFilter;
    MessageToL2CancellationStarted(
      fromAddress?: PromiseOrValue<string> | null,
      toAddress?: PromiseOrValue<BigNumberish> | null,
      selector?: PromiseOrValue<BigNumberish> | null,
      payload?: null,
      nonce?: null
    ): MessageToL2CancellationStartedEventFilter;
  };

  estimateGas: {};

  populateTransaction: {};
}
