{
 "title": "Starkgate Relayer Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "HIGH calculate the paid gas",
   "type": "timeseries",
   "description": "When calculate if the paid gas cost is valid.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(starknet_bridge_relayer_calculate_paid_gas_cost_errors{method=\"getGasCostPerTimestamp\"}[1m])"
    }
   ]
  },
  {
   "title": "HIGH invalid paid gas cost",
   "type": "timeseries",
   "description": "When the user paid the wring gas cost to the relayer.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(starknet_bridge_relayer_invalid_gas_cost_errors{method=\"checkIfAmountPaidIsValid\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "HIGH low gas cost",
   "type": "timeseries",
   "description": "When the paid gas cost can not cover the transaction execution.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(starknet_bridge_relayer_low_gas_cost_errors{method=\"checkIfGasCostCoverTheTransaction\"}[1m])"
    }
   ]
  },
  {
   "title": "Indexer requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(starknet_bridge_relayer_indexer_requests{method=\"getLastIndexedBlock\"}[1m])"
    },
    {
     "expr": "rate(starknet_bridge_relayer_indexer_errors{method=\"getLastIndexedBlock\"}[1m])"
    },
    {
     "expr": "rate(starknet_bridge_relayer_indexer_requests{method=\"getRequestWithdrawalAtBlocks\"}[1m])"
    },
    {
     "expr": "rate(starknet_bridge_relayer_indexer_errors{method=\"getRequestWithdrawalAtBlocks\"}[1m])"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(starknet_bridge_relayer_storage_requests{method=\"getLastProcessedBlock\"}[1m])"
    },
    {
     "expr": "rate(starknet_bridge_relayer_storage_errors{method=\"getLastProcessedBlock\"}[1m])"
    },
    {
     "expr": "rate(starknet_bridge_relayer_storage_requests{method=\"updateProcessedBlock\"}[1m])"
    },
    {
     "expr": "rate(starknet_bridge_relayer_storage_errors{method=\"updateProcessedBlock\"}[1m])"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "rate(starknet_bridge_relayer_gas_cost_requests{method=\"getGasCostPerTimestamp\"}[1m])"
    },
    {
     "expr": "rate(starknet_bridge_relayer_gas_cost_errors{method=\"getGasCostPerTimestamp\"}[1m])"
    }
   ]
  }
 ]
}