/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IStarknetCoreProxy,
  IStarknetCoreProxyInterface,
} from "../../../interfaces/StarknetCoreProxy.sol/IStarknetCoreProxy";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "newImplementation",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
      {
        internalType: "bool",
        name: "finalize",
        type: "bool",
      },
    ],
    name: "addImplementation",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "implementation",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newImplementation",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
      {
        internalType: "bool",
        name: "finalize",
        type: "bool",
      },
    ],
    name: "upgradeTo",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IStarknetCoreProxy__factory {
  static readonly abi = _abi;
  static createInterface(): IStarknetCoreProxyInterface {
    return new utils.Interface(_abi) as IStarknetCoreProxyInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IStarknetCoreProxy {
    return new Contract(address, _abi, signerOrProvider) as IStarknetCoreProxy;
  }
}
