/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  Governance,
  GovernanceInterface,
} from "../../Starknet.sol/Governance";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "acceptedGovernor",
        type: "address",
      },
    ],
    name: "LogNewGovernorAccepted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "nominatedGovernor",
        type: "address",
      },
    ],
    name: "LogNominatedGovernor",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [],
    name: "LogNominationCancelled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "removedGovernor",
        type: "address",
      },
    ],
    name: "LogRemovedGovernor",
    type: "event",
  },
] as const;

export class Governance__factory {
  static readonly abi = _abi;
  static createInterface(): GovernanceInterface {
    return new utils.Interface(_abi) as GovernanceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Governance {
    return new Contract(address, _abi, signerOrProvider) as Governance;
  }
}
