/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  GovernedFinalizable,
  GovernedFinalizableInterface,
} from "../../Starknet.sol/GovernedFinalizable";

const _abi = [
  {
    anonymous: false,
    inputs: [],
    name: "Finalized",
    type: "event",
  },
  {
    inputs: [],
    name: "finalize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "isFinalized",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class GovernedFinalizable__factory {
  static readonly abi = _abi;
  static createInterface(): GovernedFinalizableInterface {
    return new utils.Interface(_abi) as GovernedFinalizableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): GovernedFinalizable {
    return new Contract(address, _abi, signerOrProvider) as GovernedFinalizable;
  }
}
