/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { Identity, IdentityInterface } from "../../Starknet.sol/Identity";

const _abi = [
  {
    inputs: [],
    name: "identify",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

export class Identity__factory {
  static readonly abi = _abi;
  static createInterface(): IdentityInterface {
    return new utils.Interface(_abi) as IdentityInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Identity {
    return new Contract(address, _abi, signerOrProvider) as Identity;
  }
}
