/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IFactRegistry,
  IFactRegistryInterface,
} from "../../Starknet.sol/IFactRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "fact",
        type: "bytes32",
      },
    ],
    name: "isValid",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IFactRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IFactRegistryInterface {
    return new utils.Interface(_abi) as IFactRegistryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IFactRegistry {
    return new Contract(address, _abi, signerOrProvider) as IFactRegistry;
  }
}
