/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IStarknetMessagingEvents,
  IStarknetMessagingEventsInterface,
} from "../../Starknet.sol/IStarknetMessagingEvents";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "fromAddress",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "toAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256[]",
        name: "payload",
        type: "uint256[]",
      },
    ],
    name: "ConsumedMessageToL1",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "fromAddress",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "toAddress",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "selector",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256[]",
        name: "payload",
        type: "uint256[]",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "nonce",
        type: "uint256",
      },
    ],
    name: "ConsumedMessageToL2",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "fromAddress",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "toAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256[]",
        name: "payload",
        type: "uint256[]",
      },
    ],
    name: "LogMessageToL1",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "fromAddress",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "toAddress",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "selector",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256[]",
        name: "payload",
        type: "uint256[]",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "nonce",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "fee",
        type: "uint256",
      },
    ],
    name: "LogMessageToL2",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "fromAddress",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "toAddress",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "selector",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256[]",
        name: "payload",
        type: "uint256[]",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "nonce",
        type: "uint256",
      },
    ],
    name: "MessageToL2Canceled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "fromAddress",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "toAddress",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "selector",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256[]",
        name: "payload",
        type: "uint256[]",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "nonce",
        type: "uint256",
      },
    ],
    name: "MessageToL2CancellationStarted",
    type: "event",
  },
] as const;

export class IStarknetMessagingEvents__factory {
  static readonly abi = _abi;
  static createInterface(): IStarknetMessagingEventsInterface {
    return new utils.Interface(_abi) as IStarknetMessagingEventsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IStarknetMessagingEvents {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IStarknetMessagingEvents;
  }
}
