/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ProxySupport,
  ProxySupportInterface,
} from "../../Starknet.sol/ProxySupport";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "acceptedGovernor",
        type: "address",
      },
    ],
    name: "LogNewGovernorAccepted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "nominatedGovernor",
        type: "address",
      },
    ],
    name: "LogNominatedGovernor",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [],
    name: "LogNominationCancelled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "removedGovernor",
        type: "address",
      },
    ],
    name: "LogRemovedGovernor",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "isFrozen",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

export class ProxySupport__factory {
  static readonly abi = _abi;
  static createInterface(): ProxySupportInterface {
    return new utils.Interface(_abi) as ProxySupportInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ProxySupport {
    return new Contract(address, _abi, signerOrProvider) as ProxySupport;
  }
}
