/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../common";
import type {
  StarknetOutput,
  StarknetOutputInterface,
} from "../../Starknet.sol/StarknetOutput";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "fromAddress",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "toAddress",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "selector",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256[]",
        name: "payload",
        type: "uint256[]",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "nonce",
        type: "uint256",
      },
    ],
    name: "ConsumedMessageToL2",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "fromAddress",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "toAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256[]",
        name: "payload",
        type: "uint256[]",
      },
    ],
    name: "LogMessageToL1",
    type: "event",
  },
] as const;

const _bytecode =
  "0x60566023600b82828239805160001a607314601657fe5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220c8fb05006309fac32fb1c72b77fd481ba2e432e041b4a828fa1bd771dfee16eb64736f6c634300060c0033";

type StarknetOutputConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: StarknetOutputConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class StarknetOutput__factory extends ContractFactory {
  constructor(...args: StarknetOutputConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<StarknetOutput> {
    return super.deploy(overrides || {}) as Promise<StarknetOutput>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): StarknetOutput {
    return super.attach(address) as StarknetOutput;
  }
  override connect(signer: Signer): StarknetOutput__factory {
    return super.connect(signer) as StarknetOutput__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): StarknetOutputInterface {
    return new utils.Interface(_abi) as StarknetOutputInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): StarknetOutput {
    return new Contract(address, _abi, signerOrProvider) as StarknetOutput;
  }
}
